<DogfightGame>:
    starfield: starfield
    
    BoxLayout:
        size: (root.width, root.height)
        Starfield:
            size: (root.width, root.height)
            id: starfield
        

<GenericObject>:
    source: self.source
    canvas.before:
        PushMatrix
        Rotate:
            angle: self.angle * -1
            axis: 0, 0, 1
            origin: self.center
    canvas.after:
        PopMatrix
