<DogfightGame>:
    starfield: starfield
    
    BoxLayout:
        size: (root.width, root.height)
        Starfield:
            size: (root.width, root.height)
            id: starfield
        

<GenericObject>:
    source: root.source
    canvas.before:
        PushMatrix
        Rotate:
            angle: root.angle
            axis: 0, 0, 1
            origin: root.center
    canvas.after:
        PopMatrix
